### ISSUE TITLE
Front 개인 역할

### ISSUE THREAD

**Issue by mingnana** [ohouse-clone/ohouse_front#2]

**Comment by mingnana** [comment]
프론트팀 업무

**API 작업**
- 회원가입
- 로그인
- 사진 목록
- 게시판 글 작성
- 게시판 댓글 작성

**마크업**

- 커뮤니티
- 사진
- 집들이
- 로그인
    - 아이디 찾기
- 회원가입

**Comment by JJHeon** [comment]
**목표**
    - 오늘의집 클론 코딩 개발 및 테스트 ( ~9월 15일)
    - 배포 및 관련 내용 문서화 ( ~ 9월 15일 ~)

**백엔드**
**API**
    - 스토어 상품페이지
    - 스토어 구매페이지
    - 판매자 등록
    - 구매 API
  
**개발 환경 구축 및 관리**
    - ERD 수정 및 관리
    - AWS EC2 운영
    - AWS RDS 운영
    - Github 권한 매니지먼트

**PM**
    - 원활한 개발을 위해 스크럼 및 미팅 진행

**Comment by syp95** [comment]
**박승영 업무계획**

 - 08 24 ~ 08 28
      - ~~NextJS로 변경~~.
      - 스토어홈, 카테고리 (일부), 베스트, 상품페이지, 결제페이지(간단히) 마크업

 - 08 28 ~ 08.29
      - 상품 API 추가 / 마크업 미흡부분 보완

 - 08.29 ~ 09.03
      - 결제 페이지 (완성) / 결제 완료 페이지 / 구매내역 페이지 마크업

 - 09.04
      - 결제 API 추가 / 마크업 미흡부분 보완

 - 09.05 ~ 09.13
      - 판매자 페이지, 상품 추가 페이지, API 추가 / 최종 미흡부분 보완
