### ISSUE TITLE
개인 업무계획

### ISSUE THREAD

**Issue by mingnana** [ohouse-clone/ohouse_front#3]
**이민아 업무계획**

- 1차 - 25일(목)
    - 로그인 / 커뮤니티 마크업 React 작업
- 2차 - 28일(일)
    - 사진/집들이/회원가입 마크업 React 작업
    - 사진 api 추가
- 3차 - (9/3 ~ )
    - 클라이언트 글쓰기 마크업 React 작업
    - 회원가입-이메일인증 api 추가
    - id/pw 찾기 api 추가
- 4차 - (9/8 ~)
    - 미작업 기능 추가

**Comment by JJHeon** [comment]
**전정헌 업무계획**

- 08 21 ~ 08 23 
    - 제품게시판 API Controller & Test
        - 리뷰 X, 좋아요X
- 08 21 ~ 08 27 
    - API 문서 작성
- 08.29 ~ 08.31 
    - 구매 API Controller  & Test
- 09.01 ~ 09.03 
    - 회원 및 세션 기능 검토
    - 9월 3일부터 회원 기능
- 09.04 ~ 09.08 
    - API 부분에서 미지원되는 기능 추가 작업 (추가로 걸릴 수 있음)
- 09.09 ~ 09.13
    - AWS TEST & RDS 추가
- 09.09 ~ 
    - Github Readme 수정

**Comment by bjs07** [comment]
**백지수 업무계획**

+ 8/21~8/23 
    + User 기능 추가 및 API 테스트

+ 8/24~8/28
     + 게시판 글 작성 CRUD 개발
+ 8/28~8/31
    + 프론트까지 합친 사진 게시판 완성 및 정상 작동 여부 테스트
+ 9/1~9/5
    +회원 가입 및 로그인 개발
+ 9/5~9/9
    + 스크랩/하트/필터 기능 구현(추가 시간 소요 가능)
+ 9/10~
    + 최종 테스트

**Comment by syp95** [comment]
**박승영 업무계획**

- 08 24 ~ 08 28
      - 스토어홈, 카테고리 (일부), 베스트, 상품페이지, 결제페이지(간단히) 마크업

 - 08 28 ~ 08.29
      - 상품 API 추가 / 마크업 미흡부분 보완

 - 08.29 ~ 09.03
      - 결제 페이지 (완성) / 결제 완료 페이지 / 구매내역 페이지 마크업

 - 09.04
      - 결제 API 추가 / 마크업 미흡부분 보완

 - 09.05 ~ 09.13
      - 판매자 페이지, 상품 추가 페이지, API 추가
